#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROBOPPI_ROOT=$(cd -- "${SCRIPT_DIR}/../.." && pwd)

if [[ "${ROBOPPI_IPC_TRACE:-}" == "1" ]]; then
  echo "[demo] ROBOPPI_ROOT=${ROBOPPI_ROOT}" >&2
  if command -v git >/dev/null 2>&1; then
    SHA=$(git -C "${ROBOPPI_ROOT}" rev-parse --short HEAD 2>/dev/null || true)
    if [[ -n "${SHA}" ]]; then
      echo "[demo] ROBOPPI_HEAD=${SHA}" >&2
    fi
  fi
fi

TARGET=${TARGET:-""}
VERBOSE=${VERBOSE:-1}

usage() {
  cat <<'EOF'
Usage:
  bash examples/agents-dynamic-team/run-in-tmp.sh

Environment variables:
  TARGET   Workspace directory to create/use (default: mktemp under /tmp)
  VERBOSE  1 to pass --verbose to runner (default: 1)

Examples:
  # Default: creates a temp workspace
  bash examples/agents-dynamic-team/run-in-tmp.sh

  # Fixed workspace path
  TARGET=/tmp/roboppi-dynamic-team \
    bash examples/agents-dynamic-team/run-in-tmp.sh
EOF
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required command not found in PATH: $1" >&2
    exit 1
  }
}

need_cmd bun
need_cmd git
need_cmd claude

# ---------------------------------------------------------------------------
# Workspace setup
# ---------------------------------------------------------------------------

if [[ -z "${TARGET}" ]]; then
  TARGET=$(mktemp -d /tmp/roboppi-dynamic-team-XXXXXX)
else
  mkdir -p "${TARGET}"
fi

echo "Workspace: ${TARGET}"

mkdir -p "${TARGET}/.roboppi-loop"

# Initialize as a git repo with an initial commit so branch creation has a base ref.
if [[ ! -d "${TARGET}/.git" ]]; then
  git -C "${TARGET}" init -b main >/dev/null
fi

if [[ ! -f "${TARGET}/.gitignore" ]]; then
  cat > "${TARGET}/.gitignore" <<'GITIGNORE'
# workflow state
.roboppi-loop/
context/
.daemon-context/

# bun/node
node_modules/
dist/
GITIGNORE
fi

if [[ ! -f "${TARGET}/README.md" ]]; then
  cat > "${TARGET}/README.md" <<'README'
# multi-module-utils

Scratch repo generated by Roboppi's dynamic team demo.
README
fi

cp "${ROBOPPI_ROOT}/examples/agents-dynamic-team/request.md" \
   "${TARGET}/.roboppi-loop/request.md"

if ! git -C "${TARGET}" rev-parse --verify HEAD >/dev/null 2>&1; then
  git -C "${TARGET}" add -A
  git -C "${TARGET}" commit -m "init scratch repo" >/dev/null
fi

# Create a work branch so we don't operate on the protected main branch.
WORK_BRANCH="dynamic-team-$(date +%Y%m%d-%H%M%S)"
git -C "${TARGET}" checkout -b "${WORK_BRANCH}" >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# Run the workflow
# ---------------------------------------------------------------------------

RUNNER_ARGS=(
  "${ROBOPPI_ROOT}/src/workflow/run.ts"
  "${ROBOPPI_ROOT}/examples/agents-dynamic-team/workflow.yaml"
  --workspace "${TARGET}"
  --ipc-request-timeout "10m"
)

if [[ "${TUI:-}" == "1" ]]; then
  RUNNER_ARGS+=(--tui)
elif [[ "${VERBOSE}" == "1" ]]; then
  RUNNER_ARGS+=(--verbose)
fi

ROBOPPI_ROOT="${ROBOPPI_ROOT}" \
  CLAUDECODE= \
  bun run --cwd "${ROBOPPI_ROOT}" "${RUNNER_ARGS[@]}"

# ---------------------------------------------------------------------------
# Post-run verification
# ---------------------------------------------------------------------------

echo
echo "Verifying generated project..."

# 1. Tests must pass
( cd "${TARGET}" && bun test )

# 2. Check that both modules export the expected functions
bun -e '
  const math = await import("'"${TARGET}"'/src/math.ts");
  const str  = await import("'"${TARGET}"'/src/string-utils.ts");

  const mathFns = ["add", "subtract", "multiply", "divide"];
  const strFns  = ["capitalize", "reverse", "truncate", "slugify"];

  for (const fn of mathFns) {
    if (typeof math[fn] !== "function") {
      console.error(`Error: math.${fn} is not a function`);
      process.exit(1);
    }
  }
  for (const fn of strFns) {
    if (typeof str[fn] !== "function") {
      console.error(`Error: string-utils.${fn} is not a function`);
      process.exit(1);
    }
  }

  // Quick smoke tests
  if (math.add(1, 2) !== 3) { console.error("add(1,2) failed"); process.exit(1); }
  if (math.divide(10, 2) !== 5) { console.error("divide(10,2) failed"); process.exit(1); }
  try { math.divide(1, 0); console.error("divide(1,0) should throw"); process.exit(1); } catch {}

  if (str.capitalize("hello") !== "Hello") { console.error("capitalize failed"); process.exit(1); }
  if (str.reverse("abc") !== "cba") { console.error("reverse failed"); process.exit(1); }
  if (str.slugify("Hello World!") !== "hello-world") { console.error("slugify failed"); process.exit(1); }

  console.log("All module exports and smoke tests passed.");
'

# 3. Division by zero must throw
bun -e '
  const { divide } = await import("'"${TARGET}"'/src/math.ts");
  try {
    divide(1, 0);
    console.error("Error: divide(1, 0) should throw");
    process.exit(1);
  } catch (e) {
    if (!e.message.includes("zero")) {
      console.error("Error: expected division by zero error, got:", e.message);
      process.exit(1);
    }
    console.log("Division by zero error handling: OK");
  }
'

echo
echo "All verifications passed."
echo
echo "Done. Next steps:"
echo "  cd ${TARGET}"
echo "  bun test"
