#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROBOPPI_ROOT=$(cd -- "${SCRIPT_DIR}/../.." && pwd)

if [[ "${ROBOPPI_IPC_TRACE:-}" == "1" ]]; then
  echo "[demo] ROBOPPI_ROOT=${ROBOPPI_ROOT}" >&2
  if command -v git >/dev/null 2>&1; then
    SHA=$(git -C "${ROBOPPI_ROOT}" rev-parse --short HEAD 2>/dev/null || true)
    if [[ -n "${SHA}" ]]; then
      echo "[demo] ROBOPPI_HEAD=${SHA}" >&2
    fi
  fi
fi

TARGET=${TARGET:-""}
VERBOSE=${VERBOSE:-1}

usage() {
  cat <<'EOF'
Usage:
  bash examples/agents-review-loop-demo/run-in-tmp.sh

Environment variables:
  TARGET   Workspace directory to create/use (default: mktemp under /tmp)
  VERBOSE  1 to pass --verbose to runner (default: 1)

Examples:
  bash examples/agents-review-loop-demo/run-in-tmp.sh

  TARGET=/tmp/roboppi-agents-wordcount \
    bash examples/agents-review-loop-demo/run-in-tmp.sh
EOF
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required command not found in PATH: $1" >&2
    exit 1
  }
}

need_cmd bun
need_cmd git
need_cmd opencode
need_cmd claude

# ---------------------------------------------------------------------------
# Workspace setup
# ---------------------------------------------------------------------------

if [[ -z "${TARGET}" ]]; then
  TARGET=$(mktemp -d /tmp/roboppi-agents-wordcount-XXXXXX)
else
  mkdir -p "${TARGET}"
fi

echo "Workspace: ${TARGET}"

mkdir -p "${TARGET}/.roboppi-loop"

# Initialize as a git repo with an initial commit so branch creation has a base ref.
if [[ ! -d "${TARGET}/.git" ]]; then
  git -C "${TARGET}" init -b main >/dev/null
fi

if [[ ! -f "${TARGET}/.gitignore" ]]; then
  cat > "${TARGET}/.gitignore" <<'GITIGNORE'
# workflow state
.roboppi-loop/
context/
.daemon-context/

# bun/node
node_modules/
dist/
GITIGNORE
fi

if [[ ! -f "${TARGET}/README.md" ]]; then
  cat > "${TARGET}/README.md" <<'README'
# word-counter

Scratch repo generated by Roboppi's agents review-loop demo.
README
fi

cp "${ROBOPPI_ROOT}/examples/agents-review-loop-demo/request.md" \
   "${TARGET}/.roboppi-loop/request.md"

if ! git -C "${TARGET}" rev-parse --verify HEAD >/dev/null 2>&1; then
  git -C "${TARGET}" add -A
  git -C "${TARGET}" commit -m "init scratch repo" >/dev/null
fi

# Create a work branch so we don't operate on the protected main branch.
WORK_BRANCH="agents-review-loop-$(date +%Y%m%d-%H%M%S)"
git -C "${TARGET}" checkout -b "${WORK_BRANCH}" >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# Run the workflow
# ---------------------------------------------------------------------------

RUNNER_ARGS=(
  "${ROBOPPI_ROOT}/src/workflow/run.ts"
  "${ROBOPPI_ROOT}/examples/agents-review-loop-demo/workflow.yaml"
  --workspace "${TARGET}"
  --ipc-request-timeout "10m"
)

if [[ "${TUI:-}" == "1" ]]; then
  RUNNER_ARGS+=(--tui)
elif [[ "${VERBOSE}" == "1" ]]; then
  RUNNER_ARGS+=(--verbose)
fi

# Unset CLAUDECODE to allow nested Claude Code sessions in the demo.
ROBOPPI_ROOT="${ROBOPPI_ROOT}" \
  CLAUDECODE= \
  bun run --cwd "${ROBOPPI_ROOT}" "${RUNNER_ARGS[@]}"

# ---------------------------------------------------------------------------
# Post-run verification
# ---------------------------------------------------------------------------

echo
echo "Verifying generated repo..."

# 1. Tests must pass
( cd "${TARGET}" && bun test )

# 2. CLI must produce valid JSON with expected fields
TMPFILE=$(mktemp)
cat > "$TMPFILE" <<'SAMPLE'
The quick brown fox jumps over the lazy dog.
The quick brown fox is very quick.
SAMPLE

CLI_OUT=$(cd "${TARGET}" && bun run src/cli.ts "$TMPFILE" 2>/dev/null)
rm -f "$TMPFILE"

echo "${CLI_OUT}" | bun -e '
  const input = (await Bun.stdin.text()).trim();
  if (!input) { console.error("Error: empty CLI output"); process.exit(1); }
  const obj = JSON.parse(input);
  if (typeof obj.lines !== "number") { console.error("Error: missing lines"); process.exit(1); }
  if (typeof obj.words !== "number") { console.error("Error: missing words"); process.exit(1); }
  if (typeof obj.chars !== "number") { console.error("Error: missing chars"); process.exit(1); }
  if (!Array.isArray(obj.top_words)) { console.error("Error: missing top_words"); process.exit(1); }
  console.log("CLI output valid:", JSON.stringify(obj, null, 2));
'

# 3. Error handling: missing file should exit non-zero
if cd "${TARGET}" && bun run src/cli.ts nonexistent-file-12345.txt 2>/dev/null; then
  echo "Error: CLI should exit non-zero for missing file" >&2
  exit 1
fi

echo
echo "All verifications passed."
echo
echo "Done. Next steps:"
echo "  cd ${TARGET}"
echo "  bun test"
echo "  echo 'hello world' > sample.txt && bun run src/cli.ts sample.txt"
