# File Watcher — run tests on file changes
# Watches src/**/*.ts and runs tests with debounce
#
# NOTE: the fswatch event source is planned for Phase 2.
# This file is a configuration reference.
#
# Run: bun run src/daemon/cli.ts examples/daemon/file-watcher.yaml --verbose
name: file-watcher
version: "1"
description: "Run tests automatically when TypeScript files change"

workspace: "/tmp/roboppi-daemon-watcher"
state_dir: "/tmp/roboppi-daemon-watcher/.daemon-state"

events:
  src-change:
    type: fswatch
    paths:
      - "src/**/*.ts"
      - "src/**/*.tsx"
    ignore:
      - "**/*.test.ts"
      - "**/*.spec.ts"
      - "**/node_modules/**"
      - "**/dist/**"
    events: [create, modify]

triggers:
  auto-test:
    on: src-change
    workflow: ./workflows/test-suite.yaml
    debounce: "5s"
    cooldown: "30s"
    on_workflow_failure: ignore
