# File Watcher - Run tests on file changes
# Watches src/**/*.ts and triggers a test workflow with debounce.
#
# Start:
#   bun run src/daemon/cli.ts examples/daemon/file-watcher.yaml --verbose
name: file-watcher
version: "1"
description: "Daemon that runs tests when TypeScript files change"

workspace: "/tmp/agentcore-daemon-watcher"
state_dir: "/tmp/agentcore-daemon-watcher/.daemon-state"

events:
  src-change:
    type: fswatch
    paths:
      - "src/**/*.ts"
      - "src/**/*.tsx"
    ignore:
      - "**/*.test.ts"
      - "**/*.spec.ts"
      - "**/node_modules/**"
      - "**/dist/**"
    events: [create, modify]

triggers:
  auto-test:
    on: src-change
    workflow: ./workflows/test-suite.yaml
    debounce: "5s"
    cooldown: "30s"
    on_workflow_failure: ignore
