# Multi-Trigger — 複数イベント＋複数トリガーの daemon
# cron + interval + command の 3 つのイベントソースを使い、
# 異なるワークフローを条件付きで起動する例
#
# 起動: bun run src/daemon/cli.ts examples/daemon/multi-trigger.yaml --verbose
name: multi-trigger
version: "1"
description: "複数のイベントソースとトリガーを組み合わせる daemon"

workspace: "/tmp/agentcore-daemon-multi"
state_dir: "/tmp/agentcore-daemon-multi/.daemon-state"
max_concurrent_workflows: 2

events:
  # 30 秒ごとの定期チェック
  heartbeat:
    type: interval
    every: "30s"

  # 毎時 0 分のスケジュール実行
  hourly:
    type: cron
    schedule: "0 * * * *"

  # 外部 API の状態を 1 分ごとに確認
  api-status:
    type: command
    command: "curl -s -o /dev/null -w '%{http_code}' https://httpbin.org/status/200 2>/dev/null || echo '000'"
    interval: "1m"
    trigger_on: change

triggers:
  # --- ハートビート: 30 秒ごとにヘルスチェック ---
  health:
    on: heartbeat
    workflow: ./workflows/health-check.yaml
    on_workflow_failure: ignore

  # --- 毎時レビュー: evaluate ゲートで新コミット有無を判定 ---
  hourly-review:
    on: hourly
    workflow: ./workflows/code-review.yaml
    cooldown: "30m"

    evaluate:
      worker: CUSTOM
      instructions: |
        # 直近 1 時間以内のコミットがあるか確認
        if git rev-parse --git-dir > /dev/null 2>&1; then
          RECENT=$(git log --since="1 hour ago" --oneline 2>/dev/null | wc -l)
          if [ "$RECENT" -gt 0 ]; then
            echo "run: $RECENT new commits in the last hour"
            exit 0
          fi
        fi
        echo "skip: no recent commits"
        exit 1
      capabilities: [READ, RUN_COMMANDS]
      timeout: "10s"

    context:
      last_result: true
      event_payload: true

    analyze:
      worker: CUSTOM
      instructions: |
        echo "Hourly review completed at $(date)" > hourly-summary.txt
        echo "Status: {{workflow_status}}" >> hourly-summary.txt
      capabilities: [EDIT]
      timeout: "10s"
      outputs:
        - name: hourly-summary
          path: hourly-summary.txt

  # --- API 状態変化: ステータスコードが変わったらテスト実行 ---
  api-change:
    on: api-status
    workflow: ./workflows/test-suite.yaml
    debounce: "30s"
    cooldown: "5m"
    max_retries: 1
    on_workflow_failure: retry
