# Multi-trigger daemon
# Uses cron + interval + command event sources and triggers different workflows.
#
# Start:
#   bun run src/daemon/cli.ts examples/daemon/multi-trigger.yaml --verbose
name: multi-trigger
version: "1"
description: "Daemon combining multiple event sources and triggers"

workspace: "/tmp/agentcore-daemon-multi"
state_dir: "/tmp/agentcore-daemon-multi/.daemon-state"
max_concurrent_workflows: 2

events:
  # Periodic heartbeat every 30 seconds
  heartbeat:
    type: interval
    every: "30s"

  # Run on the hour
  hourly:
    type: cron
    schedule: "0 * * * *"

  # Check an external API status every minute
  api-status:
    type: command
    command: "curl -s -o /dev/null -w '%{http_code}' https://httpbin.org/status/200 2>/dev/null || echo '000'"
    interval: "1m"
    trigger_on: change

triggers:
  # Heartbeat -> health check
  health:
    on: heartbeat
    workflow: ./workflows/health-check.yaml
    on_workflow_failure: ignore

  # Hourly review (evaluate gate checks if there were recent commits)
  hourly-review:
    on: hourly
    workflow: ./workflows/code-review.yaml
    cooldown: "30m"

    evaluate:
      worker: CUSTOM
      instructions: |
        # Check if there are commits within the last hour
        if git rev-parse --git-dir > /dev/null 2>&1; then
          RECENT=$(git log --since="1 hour ago" --oneline 2>/dev/null | wc -l)
          if [ "$RECENT" -gt 0 ]; then
            echo "run: $RECENT new commits in the last hour"
            exit 0
          fi
        fi
        echo "skip: no recent commits"
        exit 1
      capabilities: [READ, RUN_COMMANDS]
      timeout: "10s"

    context:
      last_result: true
      event_payload: true

    analyze:
      worker: CUSTOM
      instructions: |
        echo "Hourly review completed at $(date)" > hourly-summary.txt
        echo "Status: {{workflow_status}}" >> hourly-summary.txt
      capabilities: [EDIT]
      timeout: "10s"
      outputs:
        - name: hourly-summary
          path: hourly-summary.txt

  # API status change -> run test suite
  api-change:
    on: api-status
    workflow: ./workflows/test-suite.yaml
    debounce: "30s"
    cooldown: "5m"
    max_retries: 1
    on_workflow_failure: retry
