# Simple Cron Daemon — minimal periodic run
# Runs the health-check workflow every 30 seconds
#
# Run: bun run src/daemon/cli.ts examples/daemon/simple-cron.yaml --verbose
name: simple-cron
version: "1"
description: "A simple daemon that runs a health-check every 30 seconds"

workspace: "/tmp/roboppi-daemon-simple"
state_dir: "/tmp/roboppi-daemon-simple/.daemon-state"

events:
  tick:
    type: interval
    every: "30s"

triggers:
  health-check:
    on: tick
    workflow: ./workflows/health-check.yaml
    on_workflow_failure: ignore
