# Smart Reviewer — periodic review daemon with an execution gate
# Every 5 minutes, a shell-based gate decides whether to run.
# The workflow executes only when new commits are detected.
#
# Run: bun run src/daemon/cli.ts examples/daemon/smart-reviewer.yaml --verbose
name: smart-reviewer
version: "1"
description: "Run code review only when new commits exist"

workspace: "/tmp/agentcore-daemon-reviewer"
state_dir: "/tmp/agentcore-daemon-reviewer/.daemon-state"
max_concurrent_workflows: 1

events:
  periodic:
    type: cron
    schedule: "*/5 * * * *"

triggers:
  code-review:
    on: periodic
    workflow: ./workflows/code-review.yaml
    cooldown: "5m"

    # --- Execution gate ---
    # Decide whether new commits exist.
    # exit 0 = run / exit 1 = skip
    evaluate:
      worker: CUSTOM
      instructions: |
        cd {{workspace}} 2>/dev/null || exit 1

        # Skip if not a git repository.
        git rev-parse --git-dir > /dev/null 2>&1 || exit 1

        # File that stores the last reviewed commit.
        MARKER=".daemon-state/.last-review-commit"

        CURRENT=$(git rev-parse HEAD 2>/dev/null || echo "none")
        LAST=$(cat "$MARKER" 2>/dev/null || echo "")

        if [ "$CURRENT" = "$LAST" ]; then
          echo "skip: no new commits since last review"
          exit 1
        else
          echo "run: new commits detected ($LAST → $CURRENT)"
          mkdir -p .daemon-state
          echo "$CURRENT" > "$MARKER"
          exit 0
        fi
      capabilities: [READ, RUN_COMMANDS]
      timeout: "15s"

    context:
      last_result: true

    # --- Result analysis ---
    # Generate a short summary of the workflow run.
    analyze:
      worker: CUSTOM
      instructions: |
        CONTEXT="{{context_dir}}"
        echo "=== Review Summary ===" > summary.md
        echo "Status: {{workflow_status}}" >> summary.md
        echo "Time: $(date)" >> summary.md
        echo "" >> summary.md
        if [ -d "$CONTEXT" ]; then
          echo "## Step Results" >> summary.md
          for d in "$CONTEXT"/*/; do
            STEP=$(basename "$d")
            [ "$STEP" = "_workflow.json" ] && continue
            if [ -f "$d/_meta.json" ]; then
              echo "- $STEP: $(cat "$d/_meta.json" 2>/dev/null | head -1)" >> summary.md
            fi
          done
        fi
        cat summary.md
      capabilities: [READ, EDIT]
      timeout: "30s"
      outputs:
        - name: review-summary
          path: summary.md
