#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
AGENTCORE_ROOT=$(cd -- "${SCRIPT_DIR}/../.." && pwd)

TARGET=${TARGET:-""}
VERBOSE=${VERBOSE:-1}

usage() {
  cat <<'EOF'
Usage:
  bash examples/agent-pr-loop-demo/run-in-tmp.sh

Environment variables:
  TARGET   Workspace directory to create/use (default: mktemp under /tmp)
  VERBOSE  1 to pass --verbose to runner (default: 1)

Examples:
  bash examples/agent-pr-loop-demo/run-in-tmp.sh

  TARGET=/tmp/agentcore-prloop-bun-linalg \
    bash examples/agent-pr-loop-demo/run-in-tmp.sh
EOF
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required command not found in PATH: $1" >&2
    exit 1
  }
}

need_cmd bun
need_cmd git
need_cmd opencode
need_cmd claude
need_cmd codex

if [[ -z "${TARGET}" ]]; then
  TARGET=$(mktemp -d /tmp/agentcore-prloop-bun-linalg-XXXXXX)
else
  mkdir -p "${TARGET}"
fi

echo "Workspace: ${TARGET}"

mkdir -p "${TARGET}/.agentcore-loop"

# Initialize as a git repo with an initial commit so branch creation has a base ref.
if [[ ! -d "${TARGET}/.git" ]]; then
  git -C "${TARGET}" init -b main >/dev/null
fi

if [[ ! -f "${TARGET}/.gitignore" ]]; then
  cat > "${TARGET}/.gitignore" <<'EOF'
# workflow state
.agentcore-loop/
context/
.daemon-context/

# bun/node
node_modules/
dist/
EOF
fi

if [[ ! -f "${TARGET}/README.md" ]]; then
  cat > "${TARGET}/README.md" <<'EOF'
# bun-linalg

Scratch repo generated by AgentCore's agent PR loop demo.
EOF
fi

cp "${AGENTCORE_ROOT}/examples/agent-pr-loop-demo/request.md" "${TARGET}/.agentcore-loop/request.md"

if ! git -C "${TARGET}" rev-parse --verify HEAD >/dev/null 2>&1; then
  git -C "${TARGET}" add -A
  git -C "${TARGET}" commit -m "init scratch repo" >/dev/null
fi

RUNNER_ARGS=(
  "${AGENTCORE_ROOT}/src/workflow/run.ts"
  "${AGENTCORE_ROOT}/examples/agent-pr-loop.yaml"
  --supervised
  --workspace "${TARGET}"
)

if [[ "${VERBOSE}" == "1" ]]; then
  RUNNER_ARGS+=(--verbose)
fi

AGENTCORE_ROOT="${AGENTCORE_ROOT}" \
  bun run --cwd "${AGENTCORE_ROOT}" "${RUNNER_ARGS[@]}"

echo
echo "Done. Next steps:"
echo "  cd ${TARGET}"
echo "  bun test"
echo "  bun run src/cli.ts solve --A '[[1,2],[3,4]]' --b '[5,6]'"
