#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROBOPPI_ROOT=$(cd -- "${SCRIPT_DIR}/../.." && pwd)

if [[ "${ROBOPPI_IPC_TRACE:-${AGENTCORE_IPC_TRACE:-}}" == "1" ]]; then
  echo "[demo] ROBOPPI_ROOT=${ROBOPPI_ROOT}" >&2
  if command -v git >/dev/null 2>&1; then
    SHA=$(git -C "${ROBOPPI_ROOT}" rev-parse --short HEAD 2>/dev/null || true)
    if [[ -n "${SHA}" ]]; then
      echo "[demo] ROBOPPI_HEAD=${SHA}" >&2
    fi
  fi
fi

TARGET=${TARGET:-""}
VERBOSE=${VERBOSE:-1}

usage() {
  cat <<'EOF'
Usage:
  bash examples/agent-pr-loop-demo/run-in-tmp.sh

Environment variables:
  TARGET   Workspace directory to create/use (default: mktemp under /tmp)
  VERBOSE  1 to pass --verbose to runner (default: 1)

Examples:
  bash examples/agent-pr-loop-demo/run-in-tmp.sh

  TARGET=/tmp/roboppi-prloop-bun-linalg \
    bash examples/agent-pr-loop-demo/run-in-tmp.sh
EOF
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required command not found in PATH: $1" >&2
    exit 1
  }
}

need_cmd bun
need_cmd git
need_cmd opencode
need_cmd claude

if [[ -z "${TARGET}" ]]; then
  TARGET=$(mktemp -d /tmp/roboppi-prloop-bun-linalg-XXXXXX)
else
  mkdir -p "${TARGET}"
fi

echo "Workspace: ${TARGET}"

mkdir -p "${TARGET}/.roboppi-loop"

# Initialize as a git repo with an initial commit so branch creation has a base ref.
if [[ ! -d "${TARGET}/.git" ]]; then
  git -C "${TARGET}" init -b main >/dev/null
fi

if [[ ! -f "${TARGET}/.gitignore" ]]; then
  cat > "${TARGET}/.gitignore" <<'EOF'
# workflow state
.roboppi-loop/
.agentcore-loop/
context/
.daemon-context/

# bun/node
node_modules/
dist/
EOF
fi

if [[ ! -f "${TARGET}/README.md" ]]; then
  cat > "${TARGET}/README.md" <<'EOF'
# bun-linalg

Scratch repo generated by Roboppi's agent PR loop demo.
EOF
fi

cp "${ROBOPPI_ROOT}/examples/agent-pr-loop-demo/request.md" "${TARGET}/.roboppi-loop/request.md"

if ! git -C "${TARGET}" rev-parse --verify HEAD >/dev/null 2>&1; then
  git -C "${TARGET}" add -A
  git -C "${TARGET}" commit -m "init scratch repo" >/dev/null
fi

RUNNER_ARGS=(
  "${ROBOPPI_ROOT}/src/workflow/run.ts"
  "${ROBOPPI_ROOT}/examples/agent-pr-loop.yaml"
  --workspace "${TARGET}"
)

if [[ "${VERBOSE}" == "1" ]]; then
  RUNNER_ARGS+=(--verbose)
fi

ROBOPPI_ROOT="${ROBOPPI_ROOT}" \
  bun run --cwd "${ROBOPPI_ROOT}" "${RUNNER_ARGS[@]}"

echo
echo "Verifying generated repo..."

if [[ -f "${TARGET}/.roboppi-loop/review.verdict" ]]; then
  V=$(cat "${TARGET}/.roboppi-loop/review.verdict" 2>/dev/null | tr -d '\r\n\t ')
  if [[ "${V}" != "PASS" && "${V}" != *'"decision":"complete"'* ]]; then
    echo "Error: expected review.verdict=PASS or decision=complete, got: ${V:-missing}" >&2
    exit 1
  fi
fi

( cd "${TARGET}" && bun test )

# Extra demo-only correctness checks (black-box CLI).
OUT_SOLVE=$(cd "${TARGET}" && bun run src/cli.ts solve --A '[[0,1],[0,1]]' --b '[1,2]')
if ! echo "${OUT_SOLVE}" | grep -Eq '"error"[[:space:]]*:[[:space:]]*"inconsistent"'; then
  echo "Error: expected solve() to report inconsistent for A=[[0,1],[0,1]] b=[1,2]" >&2
  echo "Got: ${OUT_SOLVE}" >&2
  exit 1
fi

( cd "${TARGET}" && bun run src/cli.ts eigen2x2 --A '[[5,0],[0,5]]' ) | bun -e '
  const input = (await Bun.stdin.text()).trim();
  const obj = JSON.parse(input || "{}");
  if (!obj.ok) process.exit(1);
  if (obj.diagonalizable !== true) process.exit(1);
  const evs = obj.eigenvectors;
  if (!Array.isArray(evs) || evs.length !== 2) process.exit(1);
  const v1 = evs[0], v2 = evs[1];
  if (!Array.isArray(v1) || !Array.isArray(v2) || v1.length !== 2 || v2.length !== 2) process.exit(1);

  function parseRat(s) {
    const m = String(s).trim().match(/^(-?\d+)(?:\/(\d+))?$/);
    if (!m) throw new Error("bad rational: " + s);
    const num = BigInt(m[1]);
    const den = m[2] ? BigInt(m[2]) : 1n;
    return { num, den };
  }
  function mul(a, b) { return { num: a.num * b.num, den: a.den * b.den }; }
  function sub(a, b) { return { num: a.num * b.den - b.num * a.den, den: a.den * b.den }; }

  const a = parseRat(v1[0]);
  const b = parseRat(v1[1]);
  const c = parseRat(v2[0]);
  const d = parseRat(v2[1]);
  const det = sub(mul(a, d), mul(b, c));
  if (det.num === 0n) process.exit(1);
'

echo
echo "Done. Next steps:"
echo "  cd ${TARGET}"
echo "  bun test"
echo "  bun run src/cli.ts solve --A '[[1,2],[3,4]]' --b '[5,6]'"
